In [1]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_hdf('./hand/hand-vj-2019-05-23/videos/handDeepCut_resnet50_handMay23shuffle1_1200.h5')
df.head()

scorer    DeepCut_resnet50_handMay23shuffle1_1200                         \
bodyparts                                   index
coords                                          x           y likelihood
0                                      384.204829  507.497386   0.594750
1                                      387.402157  513.858242   0.807043
2                                      390.011226  514.855631   0.804421
3                                      388.892329  514.417984   0.806011
4                                      382.087556  513.353363   0.669024

scorer                                                                \
bodyparts       pinky                              thumb
coords              x           y likelihood           x           y
0          260.737025  224.463477   0.349872  598.577142  464.940530
1          392.835183  508.294791   0.204508  601.172603  464.527058
2          246.135167  236.080091   0.316868  396.872739  517.725234
3          393.131876  509.100018   0.222144  599.240883  457.265136
4          229.455453  237.779009   0.213074  391.256318  515.338405

scorer
bodyparts
coords    likelihood
0           0.797825
1           0.751992
2           0.634548
3           0.655993
4           0.724124

In [13]:
#remove extra level "scorer"
df.columns = df.columns.droplevel()

In [14]:
df.head()

bodyparts       index                              pinky              \
coords              x           y likelihood           x           y
0          384.204829  507.497386   0.594750  260.737025  224.463477
1          387.402157  513.858242   0.807043  392.835183  508.294791
2          390.011226  514.855631   0.804421  246.135167  236.080091
3          388.892329  514.417984   0.806011  393.131876  509.100018
4          382.087556  513.353363   0.669024  229.455453  237.779009

bodyparts                  thumb
coords    likelihood           x           y likelihood
0           0.349872  598.577142  464.940530   0.797825
1           0.204508  601.172603  464.527058   0.751992
2           0.316868  396.872739  517.725234   0.634548
3           0.222144  599.240883  457.265136   0.655993
4           0.213074  391.256318  515.338405   0.724124

In [15]:
df.describe()

bodyparts       index                               pinky              \
coords              x           y  likelihood           x           y
count      362.000000  362.000000  362.000000  362.000000  362.000000
mean       461.960958  537.759039    0.630471  363.792242  236.663867
std        132.322158   61.819637    0.110372  128.824615  114.877935
min        133.239167  228.039419    0.268107  120.945741   20.526212
25%        379.743109  513.770389    0.563487  283.476723  164.653676
50%        436.336904  550.625420    0.642479  344.152474  220.001148
75%        531.492100  577.425260    0.703043  424.070145  255.838860
max        916.148566  662.330933    0.866039  875.263227  605.285508

bodyparts                   thumb
coords     likelihood           x           y  likelihood
count      362.000000  362.000000  362.000000  362.000000
mean         0.455979  588.248789  540.558405    0.616166
std          0.159928  118.372579   59.285484    0.109152
min          0.085266  278.500063  384.620714    0.157867
25%          0.320440  513.555315  515.618654    0.571822
50%          0.491692  584.002430  549.290035    0.637403
75%          0.576602  646.793653  570.177998    0.686248
max          0.782416  938.179576  689.623088    0.804898

In [16]:
#remove likelihood (what is that)
cols = [df.columns[i] for i in [0, 1, 3, 4, 6, 7]]
wo_likelihood = df[cols]
wo_likelihood.head(11)

bodyparts       index                   pinky                   thumb  \
coords              x           y           x           y           x
0          384.204829  507.497386  260.737025  224.463477  598.577142
1          387.402157  513.858242  392.835183  508.294791  601.172603
2          390.011226  514.855631  246.135167  236.080091  396.872739
3          388.892329  514.417984  393.131876  509.100018  599.240883
4          382.087556  513.353363  229.455453  237.779009  391.256318
5          260.431415  456.986403  216.796685  229.657917  587.039865
6          243.204553  450.428323  201.778921  221.998772  574.276566
7          346.624140  495.104963  187.022284  207.711338  565.991414
8          328.396234  483.683696  544.371100  426.545762  550.657263
9          306.334125  469.408332  163.887994  166.990289  533.835712
10         498.788211  418.226158  154.174476  137.590846  508.606268

bodyparts
coords              y
0          464.940530
1          464.527058
2          517.725234
3          457.265136
4          515.338405
5          446.900847
6          440.063178
7          438.487478
8          430.700075
9          424.392997
10         420.597557

In [17]:
wo_likelihood = wo_likelihood.unstack(0)
diffs = wo_likelihood.diff()
diffs.head(10)

bodyparts  coords
index      x       0           NaN
                   1      3.197328
                   2      2.609069
                   3     -1.118898
                   4     -6.804773
                   5   -121.656141
                   6    -17.226862
                   7    103.419587
                   8    -18.227907
                   9    -22.062108
dtype: float64

In [18]:
print(list(diffs.columns))
test = diffs.copy()
for i in range(len(diffs.columns)):
    x = diffs.columns[i]
    test = test.loc[(test[x] < 50) & (test[x] > -50)]
test.head(20)

AttributeError: 'Series' object has no attribute 'columns'

In [11]:
x = test.unstack(0)
y = list(x.index.values)
print(y)

NameError: name 'test' is not defined

In [150]:
diditwork = wo_likelihood.iloc[y]
diditwork.diff()

bodyparts        index       pinky       thumb
coords
x      6           NaN         NaN         NaN
       7    103.419587  -14.756637   -8.285152
       11   124.659537  -36.530205  -85.553844
       12  -251.668243   -1.065415  -27.627145
       13   -22.433188    2.370063  -24.414274
       14   -12.729740   10.886039  -18.975353
       15    -7.135646    6.973366  -13.734447
       17   213.881838  -33.717317    2.024009
       20    49.457509  126.343394   49.927425
       21  -180.864751   16.506029   24.837058
       23    50.973111   32.898050   45.016553
       25    47.951026   31.186945   48.362127
       26    27.708153   15.234142   22.265830
       27    28.866498   13.339266   20.973056
       28    21.123963    9.146992   23.029123
       29    17.426524    5.695413   12.692504
       30     5.786727    0.364269    2.119829
       31    -4.222201   -2.392832   -2.389091
       32    -7.000283   -4.318756   -9.583848
       33    -9.758865   -9.277105   -8.256217
       34   -11.108024   -8.930690  -12.398915
       35   -11.107583  -14.578157  -11.417392
       36   -15.259257   -9.030980  -14.143202
       37   -10.124173  -15.471098  -10.623894
       38   170.372351  -13.332959   -9.269117
       39  -180.525375  -13.693662   -4.261665
       40     9.801840  -13.460376   -1.610897
       43    26.651796  -30.028368   -0.433093
       44     1.772710   -6.795751    0.018933
       45     1.737729   -4.703226   -6.302351
...                ...         ...         ...
       330  -27.926944   -2.139643   -4.409504
       331  -27.191797    2.351843 -237.076140
       332  -26.812484    3.821484  220.383526
       333  238.261263   10.351785   -9.136801
       334  -11.118471   11.804074  -11.096780
       335   -5.713667    9.441582  -10.503830
       336   -7.828592   11.306317   -2.645933
       337  -11.544910    9.026794  -14.530838
       338   -7.254093    6.747137   -5.726819
       339   -2.528612   -1.015694   -3.440551
       340   -0.878886   -8.475074   -0.480864
       341    2.390543   -4.798568    2.424180
       343 -211.445719    3.433193    6.010709
       344   25.273079    8.166943    3.191778
       345  199.980089    7.706280    4.385132
       346    6.637939    8.748515    6.819753
       347    8.196857    8.589262    3.933478
       348    1.124231   10.368874    6.027244
       349 -158.463174    6.983882    3.952305
       350    1.717966    7.820122    3.523187
       351    2.051300    7.439096    0.992151
       352    4.161349    7.824316    4.867729
       353  168.008996    6.344879    0.686883
       354 -159.940773    8.465423    1.985112
       355  162.141005    8.376278   -1.848357
       356 -133.958501   13.386666    9.319319
       357  149.890698   24.614218    8.211594
       359   29.445922  214.506015   32.726783
       360   31.470798   31.752572   30.271165
       361   43.666629   36.184129   44.401393

[300 rows x 3 columns]